<?php
require __DIR__.'/config/bootstrap.php'; require_login();
$counts=[];
foreach(['proyek','klien','alat_sondir'] as $t)$counts[$t]=(int)$pdo->query("SELECT COUNT(*) FROM $t")->fetchColumn();
$counts['titik_sondir']=(int)$pdo->query("SELECT COUNT(*) FROM titik_sondir WHERE parent_id IS NULL")->fetchColumn();
foreach(['draft','menunggu_pemeriksaan','disetujui','diterbitkan'] as $s){$q=$pdo->prepare('SELECT COUNT(*) FROM titik_sondir WHERE status=? AND parent_id IS NULL');$q->execute([$s]);$counts[$s]=(int)$q->fetchColumn();}
$counts['alat_aktif']=(int)$pdo->query("SELECT COUNT(*) FROM alat_sondir WHERE status='aktif'")->fetchColumn();
$counts['kalibrasi']=(int)$pdo->query("SELECT COUNT(*) FROM alat_sondir WHERE tanggal_kedaluwarsa BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 30 DAY)")->fetchColumn();
$recent=$pdo->query("SELECT p.*,k.nama_klien FROM proyek p JOIN klien k ON k.id=p.klien_id ORDER BY p.created_at DESC LIMIT 5")->fetchAll();
$tests=$pdo->query("SELECT t.*,p.nama_proyek FROM titik_sondir t JOIN proyek p ON p.id=t.proyek_id WHERE t.parent_id IS NULL ORDER BY t.created_at DESC LIMIT 5")->fetchAll();
$months=$pdo->query("SELECT DATE_FORMAT(created_at,'%Y-%m') bulan,COUNT(*) jumlah FROM titik_sondir WHERE parent_id IS NULL AND created_at>=DATE_SUB(CURDATE(),INTERVAL 11 MONTH) GROUP BY bulan ORDER BY bulan")->fetchAll();
$statuses=$pdo->query("SELECT status,COUNT(*) jumlah FROM titik_sondir WHERE parent_id IS NULL GROUP BY status")->fetchAll();
$audit=$pdo->query("SELECT a.*,u.nama_lengkap FROM audit_log a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 6")->fetchAll();
$pageTitle='Dashboard'; require APP_ROOT.'/includes/header.php';
$cards=[['Proyek',$counts['proyek'],'briefcase'],['Klien',$counts['klien'],'person-vcard'],['Titik sondir',$counts['titik_sondir'],'geo-alt'],['Draft',$counts['draft'],'pencil-square'],['Menunggu pemeriksaan',$counts['menunggu_pemeriksaan'],'hourglass-split'],['Disetujui',$counts['disetujui'],'patch-check'],['Laporan terbit',$counts['diterbitkan'],'file-earmark-check'],['Alat aktif',$counts['alat_aktif'],'tools'],['Kalibrasi ≤30 hari',$counts['kalibrasi'],'exclamation-triangle']];
?>
<?php if($_SESSION['user']['username']==='admin'):?><div class="alert alert-warning d-flex align-items-center justify-content-between"><span><i class="bi bi-shield-exclamation me-2"></i>Anda masih memakai akun awal. Ganti password untuk keamanan.</span><a class="btn btn-sm btn-warning" href="<?=url('auth/change-password.php')?>">Ganti sekarang</a></div><?php endif;?>
<div class="row g-3 mb-4"><?php foreach($cards as [$label,$value,$icon]):?><div class="col-6 col-md-4 col-xl"><div class="card stat-card h-100"><div class="card-body d-flex align-items-center gap-3"><div class="stat-icon"><i class="bi bi-<?=$icon?>"></i></div><div><div class="fs-4 fw-bold"><?=$value?></div><small class="text-secondary"><?=$label?></small></div></div></div></div><?php endforeach;?></div>
<div class="row g-3 mb-4"><div class="col-lg-8"><div class="card h-100"><div class="card-header bg-white py-3 fw-semibold">Pengujian per bulan</div><div class="card-body"><canvas id="monthlyChart" height="105"></canvas></div></div></div><div class="col-lg-4"><div class="card h-100"><div class="card-header bg-white py-3 fw-semibold">Status pengujian</div><div class="card-body"><canvas id="statusChart" height="220"></canvas></div></div></div></div>
<div class="row g-3"><div class="col-xl-6"><div class="card"><div class="card-header bg-white py-3 d-flex justify-content-between"><b>Proyek terbaru</b><a href="<?=url('proyek/index.php')?>">Lihat semua</a></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Kode</th><th>Proyek</th><th>Klien</th><th>Status</th></tr></thead><tbody><?php foreach($recent as $r):?><tr><td><?=e($r['kode_proyek'])?></td><td><?=e($r['nama_proyek'])?></td><td><?=e($r['nama_klien'])?></td><td><?=status_badge($r['status'])?></td></tr><?php endforeach;?></tbody></table></div></div></div>
<div class="col-xl-6"><div class="card"><div class="card-header bg-white py-3 d-flex justify-content-between"><b>Pengujian terbaru</b><a href="<?=url('pengujian/index.php')?>">Lihat semua</a></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Titik</th><th>Proyek</th><th>Tanggal</th><th>Status</th></tr></thead><tbody><?php foreach($tests as $r):?><tr><td><?=e($r['kode_titik'])?></td><td><?=e($r['nama_proyek'])?></td><td><?=tanggal_id($r['tanggal_pengujian'])?></td><td><?=status_badge($r['status'])?></td></tr><?php endforeach;?></tbody></table></div></div></div></div>
<script>document.addEventListener('DOMContentLoaded',()=>{new Chart(document.getElementById('monthlyChart'),{type:'bar',data:{labels:<?=json_encode(array_column($months,'bulan'))?>,datasets:[{label:'Pengujian',data:<?=json_encode(array_map('intval',array_column($months,'jumlah')))?>,backgroundColor:'#1769aa',borderRadius:7}]},options:{plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{precision:0}}}}});new Chart(document.getElementById('statusChart'),{type:'doughnut',data:{labels:<?=json_encode(array_map(fn($s)=>ucwords(str_replace('_',' ',$s)),array_column($statuses,'status')))?>,datasets:[{data:<?=json_encode(array_map('intval',array_column($statuses,'jumlah')))?>,backgroundColor:['#94a3b8','#2f80ed','#f2c94c','#eb5757','#27ae60','#56ccf2','#34495e']}]},options:{plugins:{legend:{position:'bottom'}}}})});</script>
<?php require APP_ROOT.'/includes/footer.php'; ?>
