<?php
declare(strict_types=1);
require dirname(__DIR__).'/config/bootstrap.php';
require __DIR__.'/_common.php';
permohonan_ensure($pdo);$error='';
if(isset($_GET['keluar'])){unset($_SESSION['pemohon']);redirect('permohonan/index.php');}
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=(string)($_POST['action']??'');
 try{
  if($action==='daftar'){
   $name=trim((string)$_POST['nama_lengkap']);$username=trim((string)$_POST['username']);$email=trim((string)$_POST['email']);$password=(string)$_POST['password'];
   if($name===''||$username===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<8)throw new RuntimeException('Lengkapi data. Password minimal 8 karakter.');
   $pdo->prepare('INSERT INTO akun_pemohon(nama_lengkap,username,email,whatsapp,password) VALUES(?,?,?,?,?)')->execute([$name,$username,$email,trim((string)($_POST['whatsapp']??'')),password_hash($password,PASSWORD_DEFAULT)]);
   $_SESSION['pemohon']=['id'=>(int)$pdo->lastInsertId(),'nama_lengkap'=>$name,'email'=>$email];flash('success','Akun berhasil dibuat. Silakan isi permohonan.');redirect('permohonan/index.php');
  }
  if($action==='masuk'){
   $identity=trim((string)$_POST['identity']);$q=$pdo->prepare("SELECT * FROM akun_pemohon WHERE (username=? OR email=?) AND status='aktif'");$q->execute([$identity,$identity]);$account=$q->fetch();
   if(!$account||!password_verify((string)$_POST['password'],$account['password']))throw new RuntimeException('Username/email atau password salah.');
   $_SESSION['pemohon']=['id'=>(int)$account['id'],'nama_lengkap'=>$account['nama_lengkap'],'email'=>$account['email']];redirect('permohonan/index.php');
  }
  if($action==='ajukan'){
   if(!pemohon_logged_in())throw new RuntimeException('Silakan masuk terlebih dahulu.');
   $client=trim((string)$_POST['nama_klien']);$project=trim((string)$_POST['nama_proyek']);if($client===''||$project==='')throw new RuntimeException('Nama klien dan proyek wajib diisi.');
   $pdo->prepare('INSERT INTO permohonan(nomor_permohonan,pemohon_id,nama_klien,nama_perusahaan,nama_kontak,whatsapp,email,alamat_klien,kabupaten_klien,provinsi_klien,npwp,nama_proyek,nama_pekerjaan,pemilik_pekerjaan,alamat_lokasi,desa,kecamatan,kabupaten,provinsi,jumlah_titik_rencana,tanggal_rencana,catatan_pemohon) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')
    ->execute([permohonan_number($pdo),(int)$_SESSION['pemohon']['id'],$client,trim((string)($_POST['nama_perusahaan']??'')),trim((string)($_POST['nama_kontak']??'')),trim((string)($_POST['whatsapp']??'')),trim((string)($_POST['email']??'')),trim((string)($_POST['alamat_klien']??'')),trim((string)($_POST['kabupaten_klien']??'')),trim((string)($_POST['provinsi_klien']??'')),trim((string)($_POST['npwp']??'')),$project,trim((string)($_POST['nama_pekerjaan']??'')),trim((string)($_POST['pemilik_pekerjaan']??'')),trim((string)($_POST['alamat_lokasi']??'')),trim((string)($_POST['desa']??'')),trim((string)($_POST['kecamatan']??'')),trim((string)($_POST['kabupaten']??'')),trim((string)($_POST['provinsi']??'')),max(1,(int)($_POST['jumlah_titik_rencana']??1)),$_POST['tanggal_rencana']?:null,trim((string)($_POST['catatan_pemohon']??''))]);
   flash('success','Permohonan berhasil dikirim dan menunggu pemeriksaan laboratorium.');redirect('permohonan/index.php');
  }
 }catch(PDOException $e){$error=$e->getCode()==='23000'?'Username atau email sudah digunakan.':'Data tidak dapat disimpan.';}catch(Throwable $e){$error=$e->getMessage();}
}
$requests=[];if(pemohon_logged_in()){$q=$pdo->prepare('SELECT * FROM permohonan WHERE pemohon_id=? ORDER BY id DESC');$q->execute([(int)$_SESSION['pemohon']['id']]);$requests=$q->fetchAll();}
?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Portal Permohonan Sondir</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><style>
body{background:#eef4f8;color:#17324d}.portal-nav{background:#173b61}.brand-subtitle{display:block;font-size:.68rem;font-weight:500;letter-spacing:.035em;opacity:.82;margin-left:2.15rem}.hero{background:linear-gradient(135deg,#173b61,#0b7a8f);color:#fff;padding:42px 0}.institution{font-size:.88rem;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:#bfe8ef;margin-bottom:10px}.card{border:0;border-radius:16px;box-shadow:0 8px 28px rgba(23,50,77,.08)}.step{width:32px;height:32px;border-radius:50%;display:inline-grid;place-items:center;background:#0d6efd;color:#fff;font-weight:800}.required:after{content:' *';color:#dc3545}</style></head><body>
<nav class="navbar portal-nav navbar-dark"><div class="container"><a class="navbar-brand fw-bold" href="<?=url('permohonan/index.php')?>"><span><i class="bi bi-cone-striped me-2"></i>PORTAL PERMOHONAN SONDIR</span><small class="brand-subtitle">Laboratorium Teknik Sipil · Fakultas Teknik · Universitas Muhammadiyah Buton</small></a><div><?php if(pemohon_logged_in()):?><span class="text-white me-3"><?=e($_SESSION['pemohon']['nama_lengkap'])?></span><a class="btn btn-sm btn-outline-light" href="?keluar=1">Keluar</a><?php else:?><a class="btn btn-sm btn-outline-light" href="<?=url('login.php')?>">Login petugas</a><?php endif;?></div></div></nav>
<section class="hero"><div class="container"><div class="institution">Laboratorium Teknik Sipil · Fakultas Teknik · Universitas Muhammadiyah Buton</div><h1 class="fw-bold">Ajukan Pengujian Sondir Secara Online</h1><p class="mb-0">Buat akun, isi data klien dan proyek, lalu pantau status permohonan.</p></div></section>
<main class="container py-4"><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><?php if($f=$_SESSION['flash']??null):unset($_SESSION['flash']);?><div class="alert alert-<?=e($f['type'])?>"><?=e($f['message'])?></div><?php endif;?>
<?php if(!pemohon_logged_in()):?><div class="row g-4"><div class="col-lg-7"><div class="card"><div class="card-body p-4"><h3><span class="step">1</span> Buat akun pemohon</h3><form method="post" class="row g-3 mt-1"><?=csrf_field()?><input type="hidden" name="action" value="daftar"><div class="col-md-6"><label class="form-label required">Nama lengkap</label><input class="form-control" required name="nama_lengkap"></div><div class="col-md-6"><label class="form-label required">Username</label><input class="form-control" required name="username"></div><div class="col-md-6"><label class="form-label required">Email</label><input class="form-control" type="email" required name="email"></div><div class="col-md-6"><label class="form-label">WhatsApp</label><input class="form-control" name="whatsapp"></div><div class="col-md-6"><label class="form-label required">Password</label><input class="form-control" type="password" minlength="8" required name="password"></div><div class="col-12"><button class="btn btn-primary px-4">Buat akun & lanjutkan</button></div></form></div></div></div>
<div class="col-lg-5"><div class="card"><div class="card-body p-4"><h3>Sudah punya akun?</h3><form method="post" class="mt-3"><?=csrf_field()?><input type="hidden" name="action" value="masuk"><div class="mb-3"><label class="form-label">Username atau email</label><input class="form-control" required name="identity"></div><div class="mb-3"><label class="form-label">Password</label><input class="form-control" type="password" required name="password"></div><button class="btn btn-outline-primary w-100">Masuk</button></form></div></div></div></div>
<?php else:?><div class="row g-4"><div class="col-xl-8"><div class="card"><div class="card-body p-4"><h3><span class="step">2</span> Isi data permohonan</h3><form method="post" class="mt-3"><?=csrf_field()?><input type="hidden" name="action" value="ajukan">
<h5 class="border-bottom pb-2 mt-3">Data Klien</h5><div class="row g-3"><div class="col-md-6"><label class="form-label required">Nama klien</label><input class="form-control" required name="nama_klien"></div><div class="col-md-6"><label class="form-label">Perusahaan/instansi</label><input class="form-control" name="nama_perusahaan"></div><div class="col-md-6"><label class="form-label">Nama kontak</label><input class="form-control" name="nama_kontak" value="<?=e($_SESSION['pemohon']['nama_lengkap'])?>"></div><div class="col-md-3"><label class="form-label">WhatsApp</label><input class="form-control" name="whatsapp"></div><div class="col-md-3"><label class="form-label">Email</label><input class="form-control" type="email" name="email" value="<?=e($_SESSION['pemohon']['email'])?>"></div><div class="col-12"><label class="form-label">Alamat klien</label><textarea class="form-control" name="alamat_klien"></textarea></div><div class="col-md-4"><label class="form-label">Kabupaten/Kota</label><input class="form-control" name="kabupaten_klien"></div><div class="col-md-4"><label class="form-label">Provinsi</label><input class="form-control" name="provinsi_klien"></div><div class="col-md-4"><label class="form-label">NPWP</label><input class="form-control" name="npwp"></div></div>
<h5 class="border-bottom pb-2 mt-4">Data Proyek</h5><div class="row g-3"><div class="col-md-7"><label class="form-label required">Nama proyek</label><input class="form-control" required name="nama_proyek"></div><div class="col-md-5"><label class="form-label">Nama pekerjaan</label><input class="form-control" name="nama_pekerjaan" value="Pengujian Sondir"></div><div class="col-md-6"><label class="form-label">Pemilik pekerjaan</label><input class="form-control" name="pemilik_pekerjaan"></div><div class="col-md-3"><label class="form-label">Jumlah titik</label><input class="form-control" type="number" min="1" name="jumlah_titik_rencana" value="1"></div><div class="col-md-3"><label class="form-label">Tanggal rencana</label><input class="form-control" type="date" name="tanggal_rencana"></div><div class="col-12"><label class="form-label required">Alamat lokasi proyek</label><textarea class="form-control" required name="alamat_lokasi"></textarea></div><div class="col-md-3"><label class="form-label">Desa/Kelurahan</label><input class="form-control" name="desa"></div><div class="col-md-3"><label class="form-label">Kecamatan</label><input class="form-control" name="kecamatan"></div><div class="col-md-3"><label class="form-label">Kabupaten/Kota</label><input class="form-control" name="kabupaten"></div><div class="col-md-3"><label class="form-label">Provinsi</label><input class="form-control" name="provinsi"></div><div class="col-12"><label class="form-label">Catatan</label><textarea class="form-control" name="catatan_pemohon"></textarea></div><div class="col-12"><button class="btn btn-primary btn-lg"><i class="bi bi-send me-1"></i>Ajukan permohonan</button></div></div></form></div></div></div>
<div class="col-xl-4"><div class="card"><div class="card-body p-4"><h4>Status permohonan</h4><?php if(!$requests):?><p class="text-secondary">Belum ada permohonan.</p><?php endif;?><?php foreach($requests as $request):?><div class="border rounded-3 p-3 mb-3"><b><?=e($request['nomor_permohonan'])?></b><div><?=e($request['nama_proyek'])?></div><span class="badge text-bg-<?=$request['status']==='diterima'?'success':($request['status']==='ditolak'?'danger':'warning')?> mt-2"><?=e(ucwords($request['status']))?></span><?php if($request['catatan_admin']):?><p class="small mt-2 mb-0"><?=e($request['catatan_admin'])?></p><?php endif;?></div><?php endforeach;?></div></div></div></div><?php endif;?></main></body></html>
