<?php
declare(strict_types=1);
require dirname(__DIR__).'/config/bootstrap.php';require_role(['super_admin','pemeriksa']);
if($_SERVER['REQUEST_METHOD']==='POST'){
    require_role('super_admin');verify_csrf();$id=(int)($_POST['id']??0);$data=[trim((string)$_POST['kode']),trim((string)$_POST['nama_metode']),trim((string)($_POST['penulis']??'')),($_POST['tahun']??'')===''?null:(int)$_POST['tahun'],trim((string)($_POST['judul_referensi']??'')),trim((string)($_POST['parameter_dihitung']??'')),trim((string)($_POST['persamaan']??'')),trim((string)($_POST['batas_penerapan']??'')),trim((string)($_POST['satuan']??'')),trim((string)($_POST['catatan']??''))];
    if($id){$before=$pdo->prepare('SELECT * FROM metode_referensi WHERE id=?');$before->execute([$id]);$pdo->prepare('UPDATE metode_referensi SET kode=?,nama_metode=?,penulis=?,tahun=?,judul_referensi=?,parameter_dihitung=?,persamaan=?,batas_penerapan=?,satuan=?,catatan=?,updated_at=NOW() WHERE id=?')->execute([...$data,$id]);audit($pdo,'Mengubah master metode/referensi','metode_referensi',$id,$before->fetch(),$data);}else{$pdo->prepare('INSERT INTO metode_referensi(kode,nama_metode,penulis,tahun,judul_referensi,parameter_dihitung,persamaan,batas_penerapan,satuan,catatan) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute($data);$id=(int)$pdo->lastInsertId();audit($pdo,'Menambah master metode/referensi','metode_referensi',$id,null,$data);}flash('success','Metode dan referensi berhasil disimpan.');redirect('pengaturan/referensi.php');
}
$edit=null;if($id=(int)($_GET['id']??0)){$q=$pdo->prepare('SELECT * FROM metode_referensi WHERE id=?');$q->execute([$id]);$edit=$q->fetch();}$rows=$pdo->query('SELECT * FROM metode_referensi ORDER BY status,nama_metode')->fetchAll();$pageTitle='Master Metode & Referensi';require APP_ROOT.'/includes/header.php';
?>
<div class="page-heading"><div><span class="eyebrow">Traceability Teknik</span><h2>Master Metode & Referensi</h2><p>Setiap korelasi dan analisis wajib menunjuk metode, persamaan, satuan, dan batas penerapannya.</p></div></div>
<div class="row g-3"><div class="col-xl-7"><div class="card"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Kode / metode</th><th>Parameter</th><th>Referensi</th><th>Batas penerapan</th><th></th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td><b><?=e($row['kode'])?></b><small class="d-block"><?=e($row['nama_metode'])?></small></td><td><?=e($row['parameter_dihitung']?:'-')?><small class="d-block text-secondary"><?=e($row['satuan']?:'-')?></small></td><td><?=e(trim($row['penulis'].' '.$row['tahun']))?><small class="d-block"><?=e($row['judul_referensi'])?></small></td><td class="small"><?=e($row['batas_penerapan']?:'-')?></td><td><a class="btn btn-sm btn-outline-primary" href="?id=<?=$row['id']?>">Edit</a></td></tr><?php endforeach;?></tbody></table></div></div></div><div class="col-xl-5"><div class="card"><div class="card-body"><h5><?=$edit?'Edit':'Tambah'?> metode</h5><form method="post"><?=csrf_field()?><input type="hidden" name="id" value="<?=$edit['id']??0?>"><div class="row g-2"><?php foreach(['kode'=>'Kode','nama_metode'=>'Nama metode','penulis'=>'Penulis','tahun'=>'Tahun','judul_referensi'=>'Judul referensi','parameter_dihitung'=>'Parameter dihitung','satuan'=>'Satuan'] as $key=>$label):?><div class="<?=$key==='nama_metode'||$key==='judul_referensi'?'col-12':'col-md-6'?>"><label class="form-label"><?=$label?></label><input class="form-control" name="<?=$key?>" value="<?=e($edit[$key]??'')?>" <?=$key==='kode'||$key==='nama_metode'?'required':''?>></div><?php endforeach;?><div class="col-12"><label class="form-label">Persamaan</label><textarea class="form-control" name="persamaan" rows="3"><?=e($edit['persamaan']??'')?></textarea></div><div class="col-12"><label class="form-label">Batas penerapan</label><textarea class="form-control" name="batas_penerapan" rows="3"><?=e($edit['batas_penerapan']??'')?></textarea></div><div class="col-12"><label class="form-label">Catatan</label><textarea class="form-control" name="catatan" rows="2"><?=e($edit['catatan']??'')?></textarea></div></div><?php if(can('super_admin')):?><button class="btn btn-primary mt-3">Simpan metode</button><?php endif;?></form></div></div></div></div>
<?php require APP_ROOT.'/includes/footer.php';

